on: [push]
name: build
jobs:
  runTest:
    name: run unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.4.8" # Resolves to the latest point release of GHC 8.8
          cabal-version: "3.10.2.1" # Exact version of Cabal
      - run: cabal test
